from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from typing import Any

import fitz

from web.services.data_store import DataStore

PAGE_WIDTH = 612
PAGE_HEIGHT = 792
MARGIN = 54
BODY_WIDTH = PAGE_WIDTH - (MARGIN * 2)
MAX_QUERY_CHARS = 5000
MAX_CANDIDATE_CHARS = 2500


class PacketPdf:
    def __init__(self) -> None:
        self.doc = fitz.open()
        self.page = self.doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
        self.y = MARGIN

    def _new_page(self) -> None:
        self.page = self.doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
        self.y = MARGIN

    def _ensure_space(self, needed: float) -> None:
        if self.y + needed > PAGE_HEIGHT - MARGIN:
            self._new_page()

    def add_text(self, text: str, *, size: int = 10, bold: bool = False) -> None:
        font = "helv" if not bold else "hebo"
        line_height = size + 4
        max_chars = max(28, int(BODY_WIDTH / (size * 0.52)))
        lines = textwrap.wrap(
            text.replace("\n", " "),
            width=max_chars,
            replace_whitespace=True,
            drop_whitespace=True,
        ) or [""]
        self._ensure_space(len(lines) * line_height + 4)
        for line in lines:
            self.page.insert_text((MARGIN, self.y), line, fontsize=size, fontname=font)
            self.y += line_height
        self.y += 3

    def add_heading(self, text: str, *, size: int = 14) -> None:
        self._ensure_space(size + 12)
        self.add_text(text, size=size, bold=True)

    def add_rule(self) -> None:
        self._ensure_space(12)
        self.page.draw_line(
            (MARGIN, self.y),
            (PAGE_WIDTH - MARGIN, self.y),
            color=(0.72, 0.68, 0.62),
            width=0.7,
        )
        self.y += 12

    def bytes(self) -> bytes:
        return self.doc.tobytes(garbage=4, deflate=True)


def _clip(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + " [truncated]"


def build_review_packet_pdf(
    *,
    store: DataStore,
    query_id: int,
    model_slug: str,
    predictions: list[dict[str, Any]],
    feedback_rows: list[dict[str, Any]],
    actor: str,
    top_k: int,
) -> bytes:
    pdf = PacketPdf()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    filename = store.file_id_to_filename[query_id]
    query_text = store.unlabelled_texts.get(query_id, "")

    pdf.add_heading("LocalLatin Review Packet", size=18)
    pdf.add_text(f"Generated: {generated_at}")
    pdf.add_text(f"Generated by: {actor}")
    pdf.add_text(f"Query: {filename} (ID {query_id})")
    pdf.add_text(f"Model: {model_slug}")
    pdf.add_text(f"Prediction scope: top {top_k}")
    pdf.add_text("Attribution/token-map data: unavailable or omitted from this bounded packet.")
    pdf.add_rule()

    pdf.add_heading("Reviewer Outcome")
    if not feedback_rows:
        pdf.add_text("No submitted feedback for this query and model yet.")
    for row in feedback_rows:
        rank = row["correct_rank"] if row["correct_rank"] is not None else ""
        candidate = row["correct_dir"] or ""
        pdf.add_text(
            f"{row['timestamp']} | {row['reviewer']} | {row['outcome']} | "
            f"rank {rank} | {candidate}"
        )
        if row["notes"]:
            pdf.add_text(f"Notes: {row['notes']}")
    pdf.add_rule()

    pdf.add_heading("Query Text")
    pdf.add_text(_clip(query_text or "[missing query text]", MAX_QUERY_CHARS), size=9)
    pdf.add_rule()

    pdf.add_heading("Top Predictions")
    for prediction in predictions[:top_k]:
        dir_name = prediction["dir_name"]
        pdf.add_heading(
            f"Match {prediction['rank']}: {dir_name} | similarity {prediction['score']:.3f}",
            size=12,
        )
        texts = store.labelled_texts.get(dir_name, {})
        if not texts:
            pdf.add_text("Candidate text unavailable.")
            continue
        for fname, text in sorted(texts.items()):
            pdf.add_text(f"Candidate file: {fname}", bold=True)
            pdf.add_text(_clip(text or "[empty candidate text]", MAX_CANDIDATE_CHARS), size=9)

    pdf.add_rule()
    pdf.add_text("End of bounded LocalLatin review packet.", size=9)
    return pdf.bytes()
