"""Build main-text attribution reporting artifacts for the three paper models.

The input is the Run 3 operational attribution summary:

    runs/active/ig_examples_200pos_run3_operational/attribution_metrics/summary.csv

Outputs:

    overleaf_drafts/tables/attribution_metrics_main.tex
    overleaf_drafts/figures/fig_attribution_rho_loo_main.{pdf,png,tex}

The main table intentionally reports only IG and retrieval-adapted MaRC for the
three headline models. It foregrounds rho_LOO and keeps the ERASER-style
metrics as compact baseline-to-ABTT comparisons so metric disagreements remain
visible in the main text.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_SUMMARY = (
    REPO_ROOT
    / "runs/active/ig_examples_200pos_run3_operational/attribution_metrics/summary.csv"
)
DEFAULT_TABLE_OUT = REPO_ROOT / "overleaf_drafts/tables/attribution_metrics_main.tex"
DEFAULT_FIG_OUT = REPO_ROOT / "overleaf_drafts/figures/fig_attribution_rho_loo_main"

MODELS = (
    ("bowphs/LaTa", "LaTa"),
    ("bowphs/PhilTa", "PhilTa"),
    ("google/mt5-base", "mT5-base"),
)
METHODS = (
    ("ig", "IG"),
    ("retrieval_mark", "MaRC"),
)

RHO_KEY = "loo_rho"
SUFF_KEY = "suff@0.25_ratio"
COMP_KEY = "comp@0.25_ratio"
MINFRAC_KEY = "compactness@0.80"
METRIC_KEYS = (RHO_KEY, SUFF_KEY, COMP_KEY, MINFRAC_KEY)


def _mean_col(metric_key: str) -> str:
    return f"{metric_key}_mean"


def _fmt(value: float, *, signed: bool = False) -> str:
    if pd.isna(value):
        return "--"
    if signed:
        return f"{value:+.3f}"
    return f"{value:.3f}"


def _bold_if(value: float, bold: bool) -> str:
    rendered = _fmt(value)
    return rf"\textbf{{{rendered}}}" if bold else rendered


def _paired_cell(base: float, abtt: float, *, lower_is_better: bool = False) -> str:
    if pd.isna(base) or pd.isna(abtt):
        return "--"
    abtt_wins = abtt < base if lower_is_better else abtt > base
    base_text = _bold_if(base, not abtt_wins)
    abtt_text = _bold_if(abtt, abtt_wins)
    return rf"{base_text}$\rightarrow${abtt_text}"


def _load_main_rows(summary_csv: Path) -> pd.DataFrame:
    df = pd.read_csv(summary_csv)
    required_cols = {"model", "method", "variant", "n", "full_cos_mean"}
    required_cols.update(_mean_col(k) for k in METRIC_KEYS)
    missing = sorted(required_cols - set(df.columns))
    if missing:
        raise ValueError(f"{summary_csv} is missing required columns: {missing}")

    wanted_models = {m for m, _ in MODELS}
    wanted_methods = {m for m, _ in METHODS}
    sub = df[df["model"].isin(wanted_models) & df["method"].isin(wanted_methods)].copy()

    expected = len(MODELS) * len(METHODS) * 2
    if len(sub) != expected:
        found = sub[["model", "method", "variant"]].sort_values(
            ["model", "method", "variant"]
        )
        raise ValueError(
            f"expected {expected} model/method/variant rows, found {len(sub)}:\n"
            + found.to_string(index=False)
        )
    return sub


def _get(summary: pd.DataFrame, model: str, method: str, variant: str, col: str) -> float:
    row = summary[
        (summary["model"] == model)
        & (summary["method"] == method)
        & (summary["variant"] == variant)
    ]
    if row.empty:
        raise KeyError((model, method, variant, col))
    return float(row.iloc[0][col])


def render_table(summary: pd.DataFrame, out_path: Path) -> None:
    lines: list[str] = [
        "% Auto-generated by scripts/ig/build_main_attribution_artifacts.py",
        "% Edit the script, not this file.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llrrrcccc}",
        r"\toprule",
        (
            r"Model & Method & \makecell{$\rho_{\text{LOO}}$\\base} "
            r"& \makecell{$\rho_{\text{LOO}}$\\ABTT} "
            r"& \makecell{$\Delta\rho_{\text{LOO}}$} "
            r"& \makecell{Suff@25\%\\base$\rightarrow$ABTT} "
            r"& \makecell{Comp@25\%\\base$\rightarrow$ABTT} "
            r"& \makecell{MinFrac@0.80\\base$\rightarrow$ABTT} "
            r"& \makecell{ERASER\\wins} \\"
        ),
        r"\midrule",
    ]

    total_eraser_wins = 0
    total_cells = 0
    rho_wins = 0

    for model, model_label in MODELS:
        first_model_row = True
        for method, method_label in METHODS:
            base_rho = _get(summary, model, method, "baseline", _mean_col(RHO_KEY))
            abtt_rho = _get(summary, model, method, "abtt", _mean_col(RHO_KEY))
            rho_delta = abtt_rho - base_rho
            if rho_delta > 0:
                rho_wins += 1

            base_suff = _get(summary, model, method, "baseline", _mean_col(SUFF_KEY))
            abtt_suff = _get(summary, model, method, "abtt", _mean_col(SUFF_KEY))
            base_comp = _get(summary, model, method, "baseline", _mean_col(COMP_KEY))
            abtt_comp = _get(summary, model, method, "abtt", _mean_col(COMP_KEY))
            base_minfrac = _get(summary, model, method, "baseline", _mean_col(MINFRAC_KEY))
            abtt_minfrac = _get(summary, model, method, "abtt", _mean_col(MINFRAC_KEY))

            eraser_wins = int(abtt_suff > base_suff) + int(abtt_comp > base_comp) + int(
                abtt_minfrac < base_minfrac
            )
            total_eraser_wins += eraser_wins
            total_cells += 3

            model_cell = model_label if first_model_row else ""
            lines.append(
                " & ".join(
                    [
                        model_cell,
                        method_label,
                        _fmt(base_rho),
                        _bold_if(abtt_rho, abtt_rho > base_rho),
                        _fmt(rho_delta, signed=True),
                        _paired_cell(base_suff, abtt_suff),
                        _paired_cell(base_comp, abtt_comp),
                        _paired_cell(base_minfrac, abtt_minfrac, lower_is_better=True),
                        f"{eraser_wins}/3",
                    ]
                )
                + r" \\"
            )
            first_model_row = False
        if model != MODELS[-1][0]:
            lines.append(r"\addlinespace[2pt]")

    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            (
                r"\caption{\textbf{Main-text candidate attribution metrics at the "
                r"predeclared operational layers for LaTa, PhilTa, and mT5-base.} "
                r"We report 200 positive query--candidate pairs per model and the two "
                r"attribution methods used in the paper: integrated gradients (IG) "
                r"and retrieval-adapted MaRC. The primary faithfulness signal is "
                rf"$\rho_{{\text{{LOO}}}}$, which improves under ABTT in "
                rf"{rho_wins}/6 model--method cells. ERASER-style metrics are shown "
                r"compactly as baseline$\rightarrow$ABTT values using one global "
                r"headline threshold choice: Sufficiency and Comprehensiveness at "
                r"25\% of query tokens, and MinFrac at recovery threshold 0.80 "
                r"(lower is better for MinFrac; higher is better otherwise). These "
                r"are the conventional midpoint thresholds from the available sweep "
                r"grid and are retained as the global main-text setting rather than "
                r"selecting model- or method-specific thresholds; the appendix exposes "
                r"the available 10/25/50\% sufficiency/comprehensiveness sweep and "
                r"marks unavailable compactness thresholds as missing. Boldface inside the "
                r"ERASER cells marks the better variant, making disagreements visible: "
                rf"ABTT wins {total_eraser_wins}/{total_cells} ERASER-style "
                r"comparisons even though $\rho_{\text{LOO}}$ improves consistently. "
                r"Cross-variant comparisons are descriptive because ABTT changes both "
                r"the attribution scores and the cosine function being explained.}"
            ),
            r"\label{tab:attribution_metrics_main}",
            r"\end{table*}",
            "",
        ]
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def render_rho_figure(summary: pd.DataFrame, out_base: Path) -> None:
    rows: list[dict[str, object]] = []
    for model, model_label in MODELS:
        for method, method_label in METHODS:
            rows.append(
                {
                    "label": f"{model_label} / {method_label}",
                    "method": method,
                    "base": _get(summary, model, method, "baseline", _mean_col(RHO_KEY)),
                    "abtt": _get(summary, model, method, "abtt", _mean_col(RHO_KEY)),
                }
            )

    plt.style.use("seaborn-v0_8-paper")
    fig, ax = plt.subplots(figsize=(3.45, 3.0))
    y = np.arange(len(rows))[::-1]
    colors = {"ig": "#0072B2", "retrieval_mark": "#D55E00"}

    for yi, row in zip(y, rows):
        color = colors[str(row["method"])]
        base = float(row["base"])
        abtt = float(row["abtt"])
        ax.plot([base, abtt], [yi, yi], color=color, linewidth=1.4, alpha=0.85)
        ax.scatter(base, yi, s=28, facecolor="white", edgecolor=color, linewidth=1.2, zorder=3)
        ax.scatter(abtt, yi, s=34, marker="D", facecolor=color, edgecolor=color, zorder=3)

    ax.axvline(0, color="0.35", linewidth=0.8, linestyle="--")
    ax.set_yticks(y)
    ax.set_yticklabels([str(row["label"]) for row in rows], fontsize=8)
    ax.set_xlabel(r"$\rho_{\mathrm{LOO}}$ (higher is better)", fontsize=9)
    ax.set_xlim(-0.08, 0.68)
    ax.grid(axis="x", color="0.86", linewidth=0.7)
    ax.grid(axis="y", visible=False)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    from matplotlib.lines import Line2D

    legend_items = [
        Line2D(
            [0],
            [0],
            marker="o",
            color="0.25",
            markerfacecolor="white",
            markeredgecolor="0.25",
            linewidth=0,
            label="baseline",
        ),
        Line2D(
            [0],
            [0],
            marker="D",
            color="0.25",
            markerfacecolor="0.25",
            markeredgecolor="0.25",
            linewidth=0,
            label="ABTT",
        ),
    ]
    ax.legend(
        handles=legend_items,
        loc="lower center",
        bbox_to_anchor=(0.5, 1.01),
        ncol=2,
        frameon=False,
        fontsize=8,
        handletextpad=0.4,
        columnspacing=1.2,
    )
    fig.tight_layout(pad=0.4)

    out_base.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_base.with_suffix(".pdf"), bbox_inches="tight", dpi=300)
    fig.savefig(out_base.with_suffix(".png"), bbox_inches="tight", dpi=300)
    plt.close(fig)

    tex = "\n".join(
        [
            "% Auto-generated by scripts/ig/build_main_attribution_artifacts.py",
            "% Edit the script, not this file.",
            r"\begin{figure}[t]",
            r"\centering",
            rf"\includegraphics[width=\linewidth]{{figures/{out_base.name}.pdf}}",
            (
                r"\caption{\textbf{$\rho_{\text{LOO}}$ foreground view for the main "
                r"candidate-attribution result.} Each line connects the baseline "
                r"and ABTT variants for one model--method cell at the predeclared "
                r"operational attribution layer. ABTT improves the leave-one-out "
                r"rank-correlation signal in all six cells; Table~\ref{tab:attribution_metrics_main} "
                r"shows the ERASER-style disagreements that qualify this narrower "
                r"faithfulness claim.}"
            ),
            r"\label{fig:attribution_rho_loo_main}",
            r"\end{figure}",
            "",
        ]
    )
    out_base.with_suffix(".tex").write_text(tex, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary_csv", type=Path, default=DEFAULT_SUMMARY)
    parser.add_argument("--table_out", type=Path, default=DEFAULT_TABLE_OUT)
    parser.add_argument("--fig_out_base", type=Path, default=DEFAULT_FIG_OUT)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    summary = _load_main_rows(args.summary_csv)
    render_table(summary, args.table_out)
    render_rho_figure(summary, args.fig_out_base)
    print(f"Wrote {args.table_out}")
    print(f"Wrote {args.fig_out_base.with_suffix('.pdf')}")
    print(f"Wrote {args.fig_out_base.with_suffix('.png')}")
    print(f"Wrote {args.fig_out_base.with_suffix('.tex')}")


if __name__ == "__main__":
    main()
