"""Package attribution metric sweeps for appendix tables.

This script is intentionally summary-driven: it does not recompute model
forwards. It renders readable appendix tables from the wide
``attribution_metrics/summary.csv`` produced by ``run_attribution_metrics.py``
and writes a tidy long CSV for auditing.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scripts" / "ig"))

from run_attribution_metrics import (  # noqa: E402
    FULL_COS_FLOOR,
    LOO_NOISE_FLOOR,
    METHOD_LABELS,
    MODEL_SHORT,
    _latex_float,
    _metric_key,
    _pct_label,
    metric_label,
)

MAIN_MODELS = ("bowphs/LaTa", "bowphs/PhilTa", "google/mt5-base")
MAIN_METHODS = ("ig", "retrieval_mark")
SUPPLEMENTAL_METHODS = (
    "bertscore",
    "ot",
    "attention_weighted",
    "attention_standalone",
    "dla",
    "random",
    "inverse",
)
VARIANTS = ("baseline", "abtt")


def parse_float_tuple(raw: str, *, name: str) -> tuple[float, ...]:
    vals = tuple(float(x.strip()) for x in raw.split(",") if x.strip())
    if not vals:
        raise ValueError(f"{name} must contain at least one value")
    return vals


def metric_keys(
    fractions: Sequence[float],
    compactness_thresholds: Sequence[float],
) -> list[str]:
    keys = ["loo_rho"]
    keys.extend(_metric_key("suff", frac) for frac in fractions)
    keys.extend(_metric_key("comp", frac) for frac in fractions)
    keys.extend(_metric_key("compactness", threshold) for threshold in compactness_thresholds)
    return keys


def required_mean_columns(keys: Iterable[str]) -> list[str]:
    return [f"{key}_mean" for key in keys]


def build_long_summary(
    summary: pd.DataFrame,
    fractions: Sequence[float],
    compactness_thresholds: Sequence[float],
) -> pd.DataFrame:
    specs: list[tuple[str, str, float | None]] = [("rho_LOO", "loo_rho", None)]
    specs.extend(("sufficiency", _metric_key("suff", frac), float(frac)) for frac in fractions)
    specs.extend(("comprehensiveness", _metric_key("comp", frac), float(frac)) for frac in fractions)
    specs.extend(
        ("min_recovery_fraction", _metric_key("compactness", threshold), float(threshold))
        for threshold in compactness_thresholds
    )

    rows = []
    for _, src in summary.iterrows():
        base = {
            "model": src["model"],
            "method": src["method"],
            "variant": src["variant"],
            "n": int(src["n"]),
            "n_q_mean": float(src["n_q_mean"]),
            "full_cos_mean": float(src["full_cos_mean"]),
        }
        for metric, key, threshold in specs:
            mean_col = f"{key}_mean"
            std_col = f"{key}_std"
            se_col = f"{key}_se"
            n_col = f"{key}_n"
            rows.append({
                **base,
                "metric": metric,
                "metric_key": key,
                "threshold": threshold,
                "mean": float(src[mean_col]) if mean_col in summary.columns and pd.notna(src[mean_col]) else float("nan"),
                "std": float(src[std_col]) if std_col in summary.columns and pd.notna(src[std_col]) else float("nan"),
                "se": float(src[se_col]) if se_col in summary.columns and pd.notna(src[se_col]) else float("nan"),
                "metric_n": int(src[n_col]) if n_col in summary.columns and pd.notna(src[n_col]) else 0,
            })
    return pd.DataFrame(rows)


def fmt_value(value: object) -> str:
    if value is None:
        return "--"
    try:
        f = float(value)
    except (TypeError, ValueError):
        return "--"
    if np.isnan(f):
        return "--"
    return f"{f:.3f}"


def model_order(summary: pd.DataFrame) -> list[str]:
    present = set(summary["model"].astype(str))
    return [m for m in MAIN_MODELS if m in present] + sorted(present.difference(MAIN_MODELS))


def method_order(summary: pd.DataFrame, requested: Sequence[str]) -> list[str]:
    present = set(summary["method"].astype(str))
    return [m for m in requested if m in present]


def render_table(
    summary: pd.DataFrame,
    out_path: Path,
    *,
    methods: Sequence[str],
    caption: str,
    label: str,
    fractions: Sequence[float],
    compactness_thresholds: Sequence[float],
) -> None:
    keys = metric_keys(fractions, compactness_thresholds)
    colspec = "ll" + "rr" * len(keys)

    lines: list[str] = [
        "% Auto-generated by scripts/ig/package_attribution_sweep_appendix.py",
        "% Edit the script, not this file.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\resizebox{\textwidth}{!}{%",
        rf"\begin{{tabular}}{{{colspec}}}",
        r"\toprule",
    ]

    header = ["Model", "Method"]
    for key in keys:
        header.append(rf"\multicolumn{{2}}{{c}}{{{metric_label(key)}}}")
    lines.append(" & ".join(header) + r" \\")

    cmid = []
    for i, _ in enumerate(keys):
        start = 3 + 2 * i
        cmid.append(rf"\cmidrule(lr){{{start}-{start + 1}}}")
    lines.append(" ".join(cmid))

    subheader = ["", ""]
    for _ in keys:
        subheader.extend(["base", "abtt"])
    lines.append(" & ".join(subheader) + r" \\")
    lines.append(r"\midrule")

    for model in model_order(summary):
        model_rows = summary[summary["model"] == model]
        ordered_methods = method_order(model_rows, methods)
        if not ordered_methods:
            continue
        first_model_row = True
        for method in ordered_methods:
            cells = [MODEL_SHORT.get(model, model) if first_model_row else "", METHOD_LABELS.get(method, method)]
            first_model_row = False
            for key in keys:
                mean_col = f"{key}_mean"
                for variant in VARIANTS:
                    row = model_rows[(model_rows["method"] == method) & (model_rows["variant"] == variant)]
                    if row.empty or mean_col not in row.columns:
                        cells.append("--")
                    else:
                        cells.append(fmt_value(row.iloc[0][mean_col]))
            lines.append(" & ".join(cells) + r" \\")
        lines.append(r"\midrule")

    if lines[-1] == r"\midrule":
        lines[-1] = r"\bottomrule"
    lines.extend([
        r"\end{tabular}%",
        r"}",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\end{table*}",
        "",
    ])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


def write_missing_report(
    summary: pd.DataFrame,
    out_path: Path,
    *,
    keys: Sequence[str],
    models: Sequence[str],
    methods: Sequence[str],
) -> dict:
    missing_columns = [col for col in required_mean_columns(keys) if col not in summary.columns]
    present = set(zip(summary["model"], summary["method"], summary["variant"]))
    missing_cells = []
    missing_metric_cells = []
    for model in models:
        for method in methods:
            for variant in VARIANTS:
                if (model, method, variant) not in present:
                    missing_cells.append({"model": model, "method": method, "variant": variant})
                    continue
                row = summary[
                    (summary["model"] == model)
                    & (summary["method"] == method)
                    & (summary["variant"] == variant)
                ].iloc[0]
                for key in keys:
                    mean_col = f"{key}_mean"
                    n_col = f"{key}_n"
                    if mean_col not in summary.columns:
                        continue
                    metric_n = int(row[n_col]) if n_col in summary.columns and pd.notna(row[n_col]) else 0
                    if pd.isna(row[mean_col]) or metric_n <= 0:
                        missing_metric_cells.append({
                            "model": model,
                            "method": method,
                            "variant": variant,
                            "metric_key": key,
                            "reason": "missing_mean_or_zero_n",
                        })

    report = {
        "source_rows": int(len(summary)),
        "models_present": sorted(summary["model"].astype(str).unique().tolist()),
        "methods_present": sorted(summary["method"].astype(str).unique().tolist()),
        "required_metric_keys": list(keys),
        "missing_mean_columns": missing_columns,
        "missing_model_method_variant_cells": missing_cells,
        "missing_metric_cells": missing_metric_cells,
        "complete": not missing_columns and not missing_cells and not missing_metric_cells,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")
    return report


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--summary_csv", default=str(
        REPO_ROOT / "runs/active/ig_examples_200pos_run3_operational/attribution_metrics/summary.csv"
    ))
    p.add_argument("--long_out", default=str(
        REPO_ROOT / "runs/active/ig_examples_200pos_run3_operational/attribution_metrics/summary_sweep_long.csv"
    ))
    p.add_argument("--missing_report_out", default=str(
        REPO_ROOT / "runs/active/ig_examples_200pos_run3_operational/attribution_metrics/appendix_sweep_completeness.json"
    ))
    p.add_argument("--main_tex_out", default=str(
        REPO_ROOT / "overleaf_drafts/tables/attribution_metrics_sweep_main_methods.tex"
    ))
    p.add_argument("--supplemental_tex_out", default=str(
        REPO_ROOT / "overleaf_drafts/tables/attribution_metrics_sweep_supplemental_methods.tex"
    ))
    p.add_argument("--sufficiency_fractions", default="0.10,0.25,0.50")
    p.add_argument("--compactness_thresholds", default="0.70,0.80,0.90,0.95")
    p.add_argument("--strict", action="store_true",
                   help="Exit nonzero if any required sweep metric column or main cell is missing.")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    fractions = parse_float_tuple(args.sufficiency_fractions, name="--sufficiency_fractions")
    compactness_thresholds = parse_float_tuple(
        args.compactness_thresholds,
        name="--compactness_thresholds",
    )
    keys = metric_keys(fractions, compactness_thresholds)

    summary = pd.read_csv(args.summary_csv)
    summary = summary[summary["model"].isin(MAIN_MODELS)].copy()

    long_summary = build_long_summary(summary, fractions, compactness_thresholds)
    Path(args.long_out).parent.mkdir(parents=True, exist_ok=True)
    long_summary.to_csv(args.long_out, index=False)
    print(f"Wrote {args.long_out} ({len(long_summary)} rows)")

    report = write_missing_report(
        summary,
        Path(args.missing_report_out),
        keys=keys,
        models=MAIN_MODELS,
        methods=MAIN_METHODS,
    )
    if args.strict and not report["complete"]:
        missing = ", ".join(report["missing_mean_columns"])
        if not missing and report["missing_metric_cells"]:
            missing = "metric cells with missing means or metric_n=0"
        if not missing:
            missing = "model/method/variant cells"
        raise SystemExit(f"Appendix sweep is incomplete: missing {missing}")

    fraction_bits = ", ".join(f"{_pct_label(frac)}\\%" for frac in fractions)
    threshold_bits = ", ".join(f"{threshold:.2f}" for threshold in compactness_thresholds)
    shared_caption_tail = (
        r" Direction arrows are printed in the column headers. "
        r"Sufficiency and Comprehensiveness are ratio metrics at "
        rf"$\{{{fraction_bits}\}}$; MinFrac is the minimum retained query-token fraction "
        rf"needed to recover $\tau \in \{{{threshold_bits}\}}$ of the full cosine "
        r"(lower is better). "
        rf"Ratio metrics require $|S_v(q_{{\text{{full}}}}, c)| \ge {_latex_float(FULL_COS_FLOOR)}$; "
        rf"$\rho_{{\text{{LOO}}}}$ excludes $|\Delta| < {_latex_float(LOO_NOISE_FLOOR)}$. "
        r"Cells shown as -- were absent from the source summary and are listed in "
        r"\texttt{appendix\_sweep\_completeness.json}."
    )

    render_table(
        summary,
        Path(args.main_tex_out),
        methods=MAIN_METHODS,
        fractions=fractions,
        compactness_thresholds=compactness_thresholds,
        label="tab:attribution_sweep_main_methods",
        caption=(
            r"Appendix attribution sweep for the two paper-facing attribution views, "
            r"\textsc{IG} and retrieval-adapted \textsc{MaRC}, across the three main-paper models."
            + shared_caption_tail
        ),
    )
    render_table(
        summary,
        Path(args.supplemental_tex_out),
        methods=SUPPLEMENTAL_METHODS,
        fractions=fractions,
        compactness_thresholds=compactness_thresholds,
        label="tab:attribution_sweep_supplemental_methods",
        caption=(
            r"Supplemental attribution sweep for additional methods and sanity baselines. "
            r"\textit{random} and \textit{inverse} are diagnostic baselines, not paper-facing "
            r"attribution methods."
            + shared_caption_tail
        ),
    )


if __name__ == "__main__":
    main()
