"""Append pair-level attribution examples for models missing from the webapp set.

``runs/active/ig_examples/phase12f_examples.csv`` was generated by
``run_phase12f_select_pair_examples.py`` for four models only (LaTa, PhilTa,
LaBSE, Qwen3-0.6B). This script adds rows for any *other* model in
``attribution_model_config.FEATURED_MODELS`` -- currently ``google/mt5-base``
and KaLM-mini -- without renumbering or otherwise disturbing the existing rows.

Differences from the original selector:

* Thresholds come from ``attribution_model_config`` (the Run 2 layer contract)
  instead of a Phase 11 results CSV, which no longer exists on disk.
* Embeddings are read from ``runs/active/encoder_bases`` (the canonical cache)
  rather than the retired ``runs/phase9_bases`` tree.
* ``query_path``/``candidate_path`` are rebuilt against ``--data_root`` because
  the split CSV still carries the pre-move ``/u/irowerojas/localLatin/canon``
  prefix, and ``run_phase12e_pair_explanations.py`` reads those paths directly.

Example ids continue from ``max(existing) + 1`` so previously generated NPZs
stay valid.

Usage::

    python scripts/ig/select_extra_pair_examples.py \\
        --models google/mt5-base \\
                 KaLM-Embedding/KaLM-embedding-multilingual-mini-instruct-v2.5 \\
        --examples_csv runs/active/ig_examples/phase12f_examples.csv
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from attribution_model_config import model_config, model_slug  # noqa: E402
from run_phase12f_select_pair_examples import (  # noqa: E402
    BUCKET_ORDER,
    build_pair_frame,
    select_diverse_examples,
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--models", nargs="+", required=True)
    p.add_argument(
        "--examples_csv",
        type=Path,
        default=REPO_ROOT / "runs/active/ig_examples/phase12f_examples.csv",
        help="Existing examples CSV to append to (rewritten in place unless --out_csv).",
    )
    p.add_argument("--out_csv", type=Path, default=None)
    p.add_argument(
        "--split_csv",
        type=Path,
        default=REPO_ROOT / "runs/phase9/phase9_split.csv",
        help="Split CSV whose row order matches the embedding cache.",
    )
    p.add_argument(
        "--bases_root",
        type=Path,
        default=REPO_ROOT / "runs/active/encoder_bases",
    )
    p.add_argument("--hidden_mean_subdir", default="hidden_mean_tokempty")
    p.add_argument("--fallback_hidden_mean_subdir", default="hidden_mean")
    p.add_argument(
        "--data_root",
        type=Path,
        default=REPO_ROOT / "data/canon",
        help="Directory holding <folder_id>/<filename> text files.",
    )
    p.add_argument("--examples_per_bucket", type=int, default=5)
    p.add_argument("--dry_run", action="store_true")
    return p.parse_args()


def remap_paths(split_df: pd.DataFrame, data_root: Path) -> pd.DataFrame:
    """Rebuild ``path`` from ``folder_id``/``filename`` under ``data_root``.

    The split CSV predates the ``data/canon`` move, so its absolute paths no
    longer resolve. The NPZ generator reads the text files off these paths, so
    they have to point somewhere real.
    """
    out = split_df.copy()
    out["path"] = [
        str(data_root / str(folder) / str(name))
        for folder, name in zip(out["folder_id"], out["filename"])
    ]
    missing = [p for p in out["path"] if not Path(p).exists()]
    if missing:
        raise SystemExit(
            f"{len(missing)} split rows do not resolve under {data_root}; "
            f"first missing: {missing[0]}"
        )
    return out


def main() -> None:
    args = parse_args()

    existing = pd.read_csv(args.examples_csv)
    next_id = int(existing["example_id"].max()) + 1
    already = {str(m) for m in existing["model_name"].unique()}

    split_df = remap_paths(pd.read_csv(args.split_csv), args.data_root)

    frames: list[pd.DataFrame] = []
    for model_name in args.models:
        if model_name in already:
            print(f"[skip] {model_name} already present in {args.examples_csv}")
            continue
        cfg = model_config(model_name)
        baseline_row = pd.Series({"tau": float(cfg["baseline_tau"])})
        abtt_row = pd.Series({"tau": float(cfg["abtt_tau"]), "D": int(cfg["D"])})

        pair_df = build_pair_frame(
            model_name,
            cfg,
            baseline_row,
            abtt_row,
            split_df,
            REPO_ROOT / "runs",
            args.hidden_mean_subdir,
            args.fallback_hidden_mean_subdir,
            bases_root=args.bases_root,
        )

        for bucket in BUCKET_ORDER:
            bucket_df = pair_df[pair_df["bucket"] == bucket].copy()
            if bucket_df.empty:
                print(
                    f"[warn] {model_name}: no candidate pairs in bucket {bucket}; skipping",
                    file=sys.stderr,
                )
                continue
            n_keep = min(args.examples_per_bucket, len(bucket_df))
            frames.append(select_diverse_examples(bucket_df, n_keep))
        print(f"[ok] {model_name} slug={model_slug(model_name)} layer={cfg['layer']}")

    if not frames:
        print("Nothing to add.")
        return

    new_df = pd.concat(frames, ignore_index=True)
    new_df = new_df.sort_values(
        by=["model_short", "bucket", "bucket_slot"],
        key=lambda col: (
            col.map({b: i for i, b in enumerate(BUCKET_ORDER)})
            if col.name == "bucket"
            else col
        ),
    ).reset_index(drop=True)
    new_df.insert(0, "example_id", np.arange(next_id, next_id + len(new_df), dtype=np.int32))

    # Align to the existing schema; persist_attribution_methods.py rewrites
    # methods_available for every row afterwards.
    for col in existing.columns:
        if col not in new_df.columns:
            new_df[col] = ""
    new_df = new_df[list(existing.columns)]

    combined = pd.concat([existing, new_df], ignore_index=True)

    print(
        new_df.groupby(["model_short", "bucket"]).size().rename("n").reset_index().to_string(index=False)
    )
    if args.dry_run:
        print(f"[dry-run] would write {len(combined)} rows ({len(new_df)} new)")
        return

    out_csv = args.out_csv or args.examples_csv
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    combined.to_csv(out_csv, index=False)
    print(f"Wrote {len(combined)} rows ({len(new_df)} new) to {out_csv}")


if __name__ == "__main__":
    main()
