#!/usr/bin/env python3
"""Geometry versus retrieval, per model-layer (paper section "Two Geometries").

Reads (all local CSVs, no embeddings are loaded, CPU only):
  runs/active/resubmit/layer_diagnostics/geometry_per_layer.csv
      per model/layer/split/view label-free geometry (views raw, abtt_d10)
  runs/active/resubmit/results/phase_resubmit_results.csv
      per model/layer/method retrieval scores (test) and train-side selection scores

Writes:
  overleaf_drafts/tables/geometry_regimes.tex        (label tab:geometry_regimes)
  overleaf_drafts/tables/geometry_correlations.tex   (label tab:geometry_correlations)
  overleaf_drafts/figures/fig_geometry_vs_auroc.{pdf,png}
  overleaf_drafts/figures/fig_standardized_gap.{pdf,png}
  <facts_md> (default: z1_numbers.md next to this run, pass --facts_md) facts for prose drafters

Conventions: label-free geometry (top-PC share, effective rank) is read on the train
split; mean pairwise cosine is read on the test split (it is also reported on train in
the facts file); retrieval is always test. "raw" view = mean-pooled hidden states, no
correction. Top-PC share = first eigenvalue share of the centred (not L2-normalised)
embedding covariance (see scripts/resubmit/run_layer_geometry_diagnostics.py).
Standardized gap = baseline test gap (same_avg - diff_avg) / SD of all test pairwise
cosines at that layer (raw view).

Run from the repo root:
  python scripts/paper/reframe/geometry_vs_retrieval.py --facts_md <path>
Python 3.10, pandas / numpy / matplotlib / scipy only.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402
from scipy import stats  # noqa: E402

GEOM_CSV = Path("runs/active/resubmit/layer_diagnostics/geometry_per_layer.csv")
RES_CSV = Path("runs/active/resubmit/results/phase_resubmit_results.csv")
TAB_DIR = Path("overleaf_drafts/tables")
FIG_DIR = Path("overleaf_drafts/figures")
SEL_TEX = TAB_DIR / "selected_layers.tex"
HEADER = "% generated by scripts/paper/reframe/geometry_vs_retrieval.py"

MODELS = [  # id, display, type label, is_t5, colour (Okabe-Ito), marker
    ("bowphs/LaTa", "LaTa", "T5 raw", True, "#0072B2", "o"),
    ("bowphs/PhilTa", "PhilTa", "T5 raw", True, "#E69F00", "s"),
    ("google/mt5-base", "mT5-base", "T5 raw", True, "#009E73", "^"),
    ("sentence-transformers/LaBSE", "LaBSE", "BERT emb.", False, "#CC79A7", "D"),
    ("Qwen/Qwen3-Embedding-0.6B", "Qwen3-0.6B", "Decoder emb.", False, "#D55E00", "v"),
    ("KaLM-Embedding/KaLM-embedding-multilingual-mini-instruct-v2.5", "KaLM-mini",
     "Decoder emb.", False, "#56B4E9", "P"),
]
DISP = {m[0]: m[1] for m in MODELS}
ORDER = [m[1] for m in MODELS]
META = {m[1]: m for m in MODELS}
T5 = [m[1] for m in MODELS if m[3]]
NONT5 = [m[1] for m in MODELS if not m[3]]

STATS = [  # column, LaTeX label
    ("cos_te", "Mean pairwise cosine"),
    ("pc1_tr", "Top-PC share"),
    ("erank_tr", "Effective rank"),
    ("gap", "Raw cosine gap"),
    ("sgap", "Standardized gap"),
]


def load() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    g = pd.read_csv(GEOM_CSV)
    r = pd.read_csv(RES_CSV)
    g["m"] = g["model"].map(DISP)
    r["m"] = r["model"].map(DISP)
    assert g["m"].notna().all() and r["m"].notna().all(), "unknown model id"

    def gv(split, view, cols):
        sub = g[(g.split == split) & (g.view == view)][["m", "layer"] + cols]
        return sub

    base = r[r.method == "baseline"][["m", "layer", "aucroc", "gap", "same_avg", "diff_avg",
                                      "dir_acc_at_1", "overall_assignment_acc",
                                      "train_aucroc", "train_dir_acc_at_1"]]
    df = base.merge(
        gv("test", "raw", ["anisotropy_mean_cosine", "cosine_std", "pc1_variance_ratio",
                           "effective_rank_entropy"]).rename(columns={
            "anisotropy_mean_cosine": "cos_te", "cosine_std": "cossd_te",
            "pc1_variance_ratio": "pc1_te", "effective_rank_entropy": "erank_te"}),
        on=["m", "layer"], validate="1:1")
    df = df.merge(
        gv("train", "raw", ["anisotropy_mean_cosine", "pc1_variance_ratio",
                            "effective_rank_entropy"]).rename(columns={
            "anisotropy_mean_cosine": "cos_tr", "pc1_variance_ratio": "pc1_tr",
            "effective_rank_entropy": "erank_tr"}),
        on=["m", "layer"], validate="1:1")
    df = df.merge(
        gv("train", "abtt_d10", ["pc1_variance_ratio", "effective_rank_entropy",
                                 "anisotropy_mean_cosine"]).rename(columns={
            "pc1_variance_ratio": "pc1_tr_abtt", "effective_rank_entropy": "erank_tr_abtt",
            "anisotropy_mean_cosine": "cos_tr_abtt"}),
        on=["m", "layer"], validate="1:1")
    for meth, tag in [("abtt_optimal", "abtt"), ("sif_only", "sif"),
                      ("abtt_fixed", "abttfix"), ("sif_abtt_optimal", "sifabtt")]:
        sub = r[r.method == meth][["m", "layer", "aucroc", "D", "dir_acc_at_1",
                                   "overall_assignment_acc"]].rename(columns={
            "aucroc": f"auc_{tag}", "D": f"D_{tag}", "dir_acc_at_1": f"dir1_{tag}",
            "overall_assignment_acc": f"assign_{tag}"})
        df = df.merge(sub, on=["m", "layer"], validate="1:1")
    df["sgap"] = df["gap"] / df["cossd_te"]
    df["abtt_gain"] = df["auc_abtt"] - df["aucroc"]
    df["is_t5"] = df["m"].isin(T5)
    df["m"] = pd.Categorical(df["m"], ORDER, ordered=True)
    df = df.sort_values(["m", "layer"]).reset_index(drop=True)
    df["depth"] = df["layer"] / df.groupby("m", observed=True)["layer"].transform("max")
    return df, g, r


def f3(x):
    return f"{x:.3f}"


def corr(x, y):
    return stats.pearsonr(x, y)[0], stats.spearmanr(x, y)[0]


def corr_rows(df, target):
    rows = []
    for col, label in STATS:
        out = {"stat": label, "col": col}
        for grp, sub in [("all", df), ("t5", df[df.is_t5]), ("nont5", df[~df.is_t5])]:
            out[f"{grp}_r"], out[f"{grp}_rho"] = corr(sub[col], sub[target])
            out[f"{grp}_n"] = len(sub)
        lomo = {m: stats.spearmanr(df[df.m != m][col], df[df.m != m][target])[0] for m in ORDER}
        out["lomo"] = lomo
        out["lomo_min"], out["lomo_max"] = min(lomo.values()), max(lomo.values())
        rows.append(out)
    return rows


def regime_rows(df):
    rows = []
    for m in ORDER:
        s = df[df.m == m]
        peak = s.loc[s.pc1_tr.idxmax()]
        worst = s.loc[s.aucroc.idxmin()]
        rows.append(dict(
            m=m, type=META[m][2], L=int(s.layer.max()),
            cos_min=s.cos_te.min(), cos_max=s.cos_te.max(),
            sd_min=s.cossd_te.min(), sd_max=s.cossd_te.max(),
            pc1_max=s.pc1_tr.max(), erank_min=s.erank_tr.min(),
            erank_min_layer=int(s.loc[s.erank_tr.idxmin(), "layer"]),
            peak_layer=int(peak.layer), auc_peak=peak.aucroc,
            auc_min=worst.aucroc, auc_min_layer=int(worst.layer)))
    return rows


def write_regimes(rows, path):
    lines = [HEADER, r"\begin{table*}[t]", r"\centering", r"\small",
             r"\setlength{\tabcolsep}{5pt}",
             r"\begin{tabular}{llrccccrcc}", r"\toprule",
             r"& & & \multicolumn{4}{c}{\textbf{Geometry (raw view)}} & "
             r"\multicolumn{3}{c}{\textbf{Baseline test AUROC}} \\",
             r"\cmidrule(lr){4-7}\cmidrule(lr){8-10}",
             r"\textbf{Model} & \textbf{Type} & $L$ & Mean cos. & Cos.\ SD & Max PC1 & Min rank & "
             r"$\ell^{*}$ & at $\ell^{*}$ & Min (layer) \\",
             r"\midrule"]
    for i, x in enumerate(rows):
        if i == 3:
            lines.append(r"\midrule")
        lines.append(
            f"{x['m']} & {x['type']} & {x['L']} & {x['cos_min']:.2f}--{x['cos_max']:.2f} & "
            f"{x['sd_min']:.2f}--{x['sd_max']:.2f} & "
            f"{f3(x['pc1_max'])} & {x['erank_min']:.2f} & {x['peak_layer']} & "
            f"{f3(x['auc_peak'])} & {f3(x['auc_min'])} ({x['auc_min_layer']}) \\\\")
    lines += [r"\bottomrule", r"\end{tabular}",
              r"\caption{Geometry and retrieval regimes of the six encoders in the raw view "
              r"(mean-pooled hidden states with no post-hoc correction). Type: T5 raw is a T5 "
              r"encoder pretrained without a sentence-embedding objective; emb.\ marks a BERT encoder "
              r"or a decoder trained with one. $L$: number of transformer layers. Mean cos.\ and "
              r"Cos.\ SD: range over layers of the mean and the standard deviation of the cosine "
              r"over all pairs of test passages. Max PC1: peak top-PC share over layers, the largest "
              r"share of variance on the first principal component of the centered train embeddings. "
              r"Min rank: smallest entropy effective rank of the same centered train embeddings over "
              r"layers. All four geometry columns are label-free. $\ell^{*}$: "
              r"layer where the PC1 share peaks. The last two columns give the baseline test "
              r"pairwise AUROC of cosine at $\ell^{*}$ and its minimum over layers, with the layer "
              r"in parentheses. Layer 1 is the first transformer block.}",
              r"\label{tab:geometry_regimes}", r"\end{table*}"]
    path.write_text("\n".join(lines) + "\n")


def write_correlations(rows_auc, rows_gain, path):
    def block(rows):
        out = []
        for x in rows:
            vals = [x["all_r"], x["all_rho"], x["t5_r"], x["t5_rho"], x["nont5_r"],
                    x["nont5_rho"], x["lomo_min"], x["lomo_max"]]
            out.append(x["stat"] + " & " + " & ".join(f"${v:+.2f}$".replace("+", "\\phantom{-}") for v in vals) + r" \\")
        return out

    lines = [HEADER, r"\begin{table*}[t]", r"\centering", r"\small",
             r"\setlength{\tabcolsep}{5pt}",
             r"\begin{tabular}{lrrrrrrrr}", r"\toprule",
             r"& \multicolumn{2}{c}{\textbf{All} (100)} & \multicolumn{2}{c}{\textbf{T5} (36)} & "
             r"\multicolumn{2}{c}{\textbf{Non-T5} (64)} & \multicolumn{2}{c}{\textbf{LOMO} $\rho$} \\",
             r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}",
             r"\textbf{Statistic} & $r$ & $\rho$ & $r$ & $\rho$ & $r$ & $\rho$ & min & max \\",
             r"\midrule",
             r"\multicolumn{9}{l}{\emph{Target: baseline AUROC}} \\"]
    lines += block(rows_auc)
    lines += [r"\midrule", r"\multicolumn{9}{l}{\emph{Target: ABTT AUROC gain}} \\"]
    lines += block(rows_gain)
    lines += [r"\bottomrule", r"\end{tabular}",
              r"\caption{Correlation between per-layer geometry and retrieval, one observation per "
              r"model-layer, raw view. $r$: Pearson; $\rho$: Spearman. Columns pool all 100 "
              r"model-layers, the 36 layers of the three T5 encoders, or the 64 layers of the three "
              r"embedding-trained models; LOMO gives the minimum and maximum Spearman over the six "
              r"leave-one-model-out subsets. Mean pairwise cosine is on test passages; top-PC share and "
              r"effective rank are on centered train embeddings. These three statistics are label-free. "
              r"The two gaps are label-based separation indices. Raw cosine gap is the mean test cosine "
              r"of same-directory pairs minus that of different-directory pairs; standardized gap "
              r"divides it by the standard deviation of all test pairwise cosines at that layer. "
              r"Targets are the baseline test AUROC and the ABTT gain (AUROC with ABTT at its "
              r"train-selected $D$ minus baseline AUROC). The standardized gap is a signal-to-noise "
              r"ratio of the kind AUROC summarizes, so it tracks AUROC by construction. ABTT AUROC "
              r"varies little (0.962--0.987), so the gain correlations mirror the baseline ones. The "
              r"pooled Pearson and Spearman values are both inflated by the two clusters of collapsed "
              r"and healthy layers, and layers within a model are not independent.}",
              r"\label{tab:geometry_correlations}", r"\end{table*}"]
    path.write_text("\n".join(lines) + "\n")


def style():
    plt.rcParams.update({
        "font.size": 8, "axes.labelsize": 8, "axes.titlesize": 8.5, "xtick.labelsize": 8,
        "ytick.labelsize": 8, "legend.fontsize": 8, "pdf.fonttype": 42, "ps.fonttype": 42,
        "axes.spines.top": False, "axes.spines.right": False, "axes.linewidth": 0.6,
        "grid.linewidth": 0.4, "grid.color": "#dddddd"})


def legend_handles(line=False):
    hs = []
    for mid, name, _, t5, col, mk in MODELS:
        hs.append(Line2D([0], [0], color=col if line else "none", marker=mk, markersize=5,
                         markerfacecolor=col if t5 else "white", markeredgecolor=col,
                         markeredgewidth=1.1, lw=1.2 if line else 0,
                         linestyle=("-" if t5 else "--") if line else "none", label=name))
    return hs


def fig_scatter(df, out):
    fig, axes = plt.subplots(1, 2, figsize=(6.3, 2.55), sharey=True)
    for ax, col, xl, pos in [(axes[0], "pc1_tr", "Top-PC share (centered, train)", (0.30, 0.42)),
                             (axes[1], "cos_te", "Mean pairwise cosine (test)", (0.03, 0.62))]:
        for mid, name, _, t5, c, mk in MODELS:
            s = df[df.m == name]
            ax.scatter(s[col], s.aucroc, marker=mk, s=22, linewidths=1.0,
                       facecolors=c if t5 else "white", edgecolors=c, zorder=3,
                       alpha=0.9 if t5 else 1.0)
        rho = stats.spearmanr(df[col], df.aucroc)[0]
        ax.set_xlabel(xl)
        ax.grid(True, zorder=0)
        ax.text(*pos, rf"Spearman $\rho$ = {rho:+.2f} (all 100)".replace("-", "\u2212"), transform=ax.transAxes,
                fontsize=8, ha="left", va="bottom")
        ax.set_xlim(-0.02, 1.02)
    axes[0].set_ylabel("Baseline test AUROC")
    axes[0].set_title("(a) Top-PC share", loc="left")
    axes[1].set_title("(b) Mean pairwise cosine", loc="left")
    fig.legend(handles=legend_handles(), loc="upper center", ncol=6, frameon=False,
               bbox_to_anchor=(0.5, 1.0), handletextpad=0.3, columnspacing=1.2)
    fig.tight_layout(rect=(0, 0, 1, 0.9), w_pad=1.2)
    fig.savefig(out.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(out.with_suffix(".png"), dpi=300, bbox_inches="tight")
    plt.close(fig)


def fig_sgap(df, out):
    fig, axes = plt.subplots(1, 3, figsize=(6.3, 2.35))
    panels = [("gap", "Raw cosine gap", "(a) Raw gap"),
              ("sgap", "Standardized gap (gap / SD)", "(b) Standardized gap"),
              ("aucroc", "Baseline test AUROC", "(c) Baseline AUROC")]
    for ax, (col, yl, title) in zip(axes, panels):
        for mid, name, _, t5, c, mk in MODELS:
            s = df[df.m == name]
            ax.plot(s.depth * 100, s[col], color=c, lw=1.2, linestyle="-" if t5 else "--",
                    marker=mk, markersize=3.2, markerfacecolor=c if t5 else "white",
                    markeredgecolor=c, markeredgewidth=0.8, zorder=3)
        ax.set_xlabel("Layer depth (%)")
        ax.set_ylabel(yl)
        ax.set_title(title, loc="left")
        ax.set_xlim(0, 102)
        ax.set_xticks([0, 25, 50, 75, 100])
        ax.grid(True, zorder=0)
        if col != "aucroc":
            ax.axhline(0, color="#888888", lw=0.6, zorder=1)
    fig.legend(handles=legend_handles(line=True), loc="upper center", ncol=6, frameon=False,
               bbox_to_anchor=(0.5, 1.0), handletextpad=0.3, columnspacing=1.2, handlelength=2.2)
    fig.tight_layout(rect=(0, 0, 1, 0.88), w_pad=0.8)
    fig.savefig(out.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(out.with_suffix(".png"), dpi=300, bbox_inches="tight")
    plt.close(fig)


def parse_selected_layers():
    """Rows of selected_layers.tex: model -> {taskA_base, taskA_abtt, taskB_base, taskB_abtt}."""
    out = {}
    if not SEL_TEX.exists():
        return out
    for line in SEL_TEX.read_text().splitlines():
        cells = [c.strip() for c in line.rstrip("\\ ").split("&")]
        if len(cells) == 9 and cells[0] in ORDER and all(re.fullmatch(r"\d+", c) for c in cells[1:]):
            v = list(map(int, cells[1:]))
            out[cells[0]] = dict(A_base=v[0], A_sif=v[1], A_abtt=v[2], A_sifabtt=v[3],
                                 B_base=v[4], B_sif=v[5], B_abtt=v[6], B_sifabtt=v[7])
    return out


def argmax_layer(r, m, method, col):
    s = r[(r.m == m) & (r.method == method)].sort_values("layer")
    return int(s.loc[s[col].idxmax(), "layer"])  # first max = earliest layer on ties


def facts(df, r, reg, ca, cg, path):
    L = []
    w = L.append
    w("# Z1 numbers: geometry versus retrieval (generated)")
    w("")
    w("Generated by `scripts/paper/reframe/geometry_vs_retrieval.py` from "
      "`geometry_per_layer.csv` and `phase_resubmit_results.csv`. Retrieval is test; "
      "top-PC share / effective rank are train (centred, raw view unless marked abtt_d10). "
      "`Mean pairwise cosine` is the mean over ALL test passage pairs (the upstream column is "
      "named anisotropy_mean_cosine; it is not a random-pair sample). AUROC 3 dp, rank 2 dp.")
    w("")
    w("## Panel check")
    for m in ORDER:
        s = df[df.m == m]
        w(f"- {m}: {len(s)} layers (1..{s.layer.max()})")
    w(f"- total model-layers: {len(df)} (T5 {int(df.is_t5.sum())}, non-T5 {int((~df.is_t5).sum())}). "
      "Matches the brief's 100.")
    w("- Model ids: " + ", ".join(f"{m[1]} = `{m[0]}`" for m in MODELS))
    w("")
    w("## Table: geometry_regimes (tab:geometry_regimes)")
    w("| Model | Type | L | cos range (test) | cos SD range (test) | max PC1 (train) | min eff rank (train, layer) | PC1-peak layer | AUROC at peak | min AUROC (layer) |")
    w("|---|---|---|---|---|---|---|---|---|---|")
    for x in reg:
        w(f"| {x['m']} | {x['type']} | {x['L']} | {x['cos_min']:.3f}-{x['cos_max']:.3f} | "
          f"{x['sd_min']:.3f}-{x['sd_max']:.3f} | "
          f"{f3(x['pc1_max'])} | {x['erank_min']:.2f} ({x['erank_min_layer']}) | {x['peak_layer']} | "
          f"{f3(x['auc_peak'])} | {f3(x['auc_min'])} ({x['auc_min_layer']}) |")
    w("")
    for title, rows in [("baseline test AUROC", ca), ("ABTT AUROC gain (abtt_optimal - baseline)", cg)]:
        w(f"## Table: geometry_correlations, target = {title}")
        w("| statistic | all r | all rho | T5 r | T5 rho | non-T5 r | non-T5 rho | LOMO rho min | LOMO rho max |")
        w("|---|---|---|---|---|---|---|---|---|")
        for x in rows:
            w(f"| {x['stat']} | {x['all_r']:+.3f} | {x['all_rho']:+.3f} | {x['t5_r']:+.3f} | "
              f"{x['t5_rho']:+.3f} | {x['nont5_r']:+.3f} | {x['nont5_rho']:+.3f} | "
              f"{x['lomo_min']:+.3f} | {x['lomo_max']:+.3f} |")
        w("")
        w("LOMO Spearman per held-out model:")
        for x in rows:
            w(f"- {x['stat']}: " + ", ".join(f"without {k} {v:+.3f}" for k, v in x["lomo"].items()))
        w("")

    # Sensitivity: geometry on the test split instead of train.
    w("## Sensitivity: same correlations with test-split geometry (baseline AUROC)")
    for col, lab in [("pc1_te", "top-PC share (test)"), ("erank_te", "effective rank (test)"),
                     ("cos_tr", "mean pairwise cosine (train)")]:
        a = corr(df[col], df.aucroc)
        n = corr(df[~df.is_t5][col], df[~df.is_t5].aucroc)
        t = corr(df[df.is_t5][col], df[df.is_t5].aucroc)
        w(f"- {lab}: all r {a[0]:+.3f} / rho {a[1]:+.3f}; T5 r {t[0]:+.3f} / rho {t[1]:+.3f}; "
          f"non-T5 r {n[0]:+.3f} / rho {n[1]:+.3f}")
    w("")

    w("## T5 collapsed layers (baseline AUROC < 0.70)")
    for m in T5:
        s = df[df.m == m]
        c = s[s.aucroc < 0.70]
        worst = s.loc[s.aucroc.idxmin()]
        w(f"### {m}")
        w(f"- collapsed layers: {c.layer.min()}-{c.layer.max()} ({len(c)} layers; "
          f"list {c.layer.tolist()}); baseline AUROC range there {f3(c.aucroc.min())}-{f3(c.aucroc.max())}")
        w(f"- worst layer {int(worst.layer)}: baseline AUROC {f3(worst.aucroc)}, top-PC share "
          f"{f3(worst.pc1_tr)} (train raw) -> {f3(worst.pc1_tr_abtt)} (abtt_d10), eff rank "
          f"{worst.erank_tr:.2f} -> {worst.erank_tr_abtt:.2f}, SIF-only AUROC {f3(worst.auc_sif)}, "
          f"ABTT (abtt_optimal, D={int(worst.D_abtt)}) AUROC {f3(worst.auc_abtt)}")
        w(f"- over collapsed layers: top-PC share raw {f3(c.pc1_tr.min())}-{f3(c.pc1_tr.max())} -> "
          f"abtt_d10 {f3(c.pc1_tr_abtt.min())}-{f3(c.pc1_tr_abtt.max())}; eff rank raw "
          f"{c.erank_tr.min():.2f}-{c.erank_tr.max():.2f} -> abtt_d10 "
          f"{c.erank_tr_abtt.min():.2f}-{c.erank_tr_abtt.max():.2f}")
        w(f"- over collapsed layers: SIF-only AUROC {f3(c.auc_sif.min())}-{f3(c.auc_sif.max())}; "
          f"ABTT-optimal AUROC {f3(c.auc_abtt.min())}-{f3(c.auc_abtt.max())}; "
          f"mean pairwise cosine (test) {c.cos_te.min():.3f}-{c.cos_te.max():.3f}")
        w(f"- best ABTT-optimal AUROC over all layers {f3(s.auc_abtt.max())} (layer "
          f"{int(s.loc[s.auc_abtt.idxmax(), 'layer'])}); worst-baseline-layer ABTT is "
          f"{(s.auc_abtt.max() - worst.auc_abtt) * 100:.2f} AUROC points below it")
        w("- per collapsed layer (layer: base / SIF / ABTT-opt / PC1 raw / PC1 abtt / rank raw / rank abtt):")
        for _, x in c.iterrows():
            w(f"  - {int(x.layer)}: {f3(x.aucroc)} / {f3(x.auc_sif)} / {f3(x.auc_abtt)} / "
              f"{f3(x.pc1_tr)} / {f3(x.pc1_tr_abtt)} / {x.erank_tr:.2f} / {x.erank_tr_abtt:.2f}")
    w("")
    w("### T5 non-collapsed layers with high top-PC share (counterexamples to watch)")
    hi = df[df.is_t5 & (df.aucroc >= 0.70) & (df.pc1_tr > 0.5)]
    for _, x in hi.iterrows():
        w(f"- {x.m} layer {int(x.layer)}: top-PC share {f3(x.pc1_tr)}, eff rank {x.erank_tr:.2f}, "
          f"baseline AUROC {f3(x.aucroc)}")
    if hi.empty:
        w("- none")
    w("")

    w("## Non-T5 models: geometry ranges (raw)")
    for m in NONT5:
        s = df[df.m == m]
        w(f"- {m}: mean pairwise cosine test {s.cos_te.min():.3f}-{s.cos_te.max():.3f} "
          f"(train {s.cos_tr.min():.3f}-{s.cos_tr.max():.3f}); top-PC share train "
          f"{f3(s.pc1_tr.min())}-{f3(s.pc1_tr.max())} (test {f3(s.pc1_te.min())}-{f3(s.pc1_te.max())}); "
          f"eff rank train {s.erank_tr.min():.2f}-{s.erank_tr.max():.2f} "
          f"(test {s.erank_te.min():.2f}-{s.erank_te.max():.2f}); baseline AUROC "
          f"{f3(s.aucroc.min())}-{f3(s.aucroc.max())}")
    nt = df[~df.is_t5]
    w(f"- all non-T5 pooled: cos test {nt.cos_te.min():.3f}-{nt.cos_te.max():.3f}; "
      f"eff rank train {nt.erank_tr.min():.2f}-{nt.erank_tr.max():.2f} (test "
      f"{nt.erank_te.min():.2f}-{nt.erank_te.max():.2f})")
    t5 = df[df.is_t5]
    w(f"- all T5 pooled: cos test {t5.cos_te.min():.3f}-{t5.cos_te.max():.3f}")
    w("")

    w("## Key correlations for prose")
    rs, rr = stats.spearmanr(df.sgap, df.aucroc)[0], stats.spearmanr(df.gap, df.aucroc)[0]
    w(f"- standardized gap vs baseline AUROC, all 100: Spearman {rs:+.3f} (Pearson "
      f"{stats.pearsonr(df.sgap, df.aucroc)[0]:+.3f}); raw gap: Spearman {rr:+.3f} (Pearson "
      f"{stats.pearsonr(df.gap, df.aucroc)[0]:+.3f})")
    w(f"- within non-T5 (64): mean pairwise cosine (test) vs baseline AUROC Pearson "
      f"{stats.pearsonr(nt.cos_te, nt.aucroc)[0]:+.3f}, Spearman {stats.spearmanr(nt.cos_te, nt.aucroc)[0]:+.3f}")
    w(f"- top-PC share (train) vs baseline AUROC, all 100: Pearson "
      f"{stats.pearsonr(df.pc1_tr, df.aucroc)[0]:+.3f}, Spearman {stats.spearmanr(df.pc1_tr, df.aucroc)[0]:+.3f}")
    mt = df[df.m == "mT5-base"]
    w("- mT5 paradox (layer: raw gap / standardized gap / baseline AUROC / cosine SD): " +
      "; ".join(f"{int(x.layer)}: {x.gap:.3f} / {x.sgap:.3f} / {f3(x.aucroc)} / {x.cossd_te:.3f}"
                for _, x in mt.iterrows()))
    w(f"- mT5 within-model Spearman vs AUROC: raw gap {stats.spearmanr(mt.gap, mt.aucroc)[0]:+.3f}, "
      f"standardized gap {stats.spearmanr(mt.sgap, mt.aucroc)[0]:+.3f}")
    w("")

    w("## ABTT")
    dcount = df.D_abtt.value_counts().sort_index()
    scount = df.D_sifabtt.value_counts().sort_index()
    w(f"- D selected by abtt_optimal (train rank-1 directory accuracy over grid "
      f"{{1,2,3,5,7,10}}): " + ", ".join(f"D={int(k)}: {v}" for k, v in dcount.items()))
    w(f"- D selected by sif_abtt_optimal: " + ", ".join(f"D={int(k)}: {v}" for k, v in scount.items()))
    w("- NOTE: D=10 is the largest value in the grid, so these counts sit on the grid boundary.")
    w(f"- abtt_optimal AUROC over all 100 cells: {f3(df.auc_abtt.min())}-{f3(df.auc_abtt.max())} "
      f"(min at {df.loc[df.auc_abtt.idxmin(), 'm']} layer {int(df.loc[df.auc_abtt.idxmin(), 'layer'])}); "
      f"abtt_fixed (D=10): {f3(df.auc_abttfix.min())}-{f3(df.auc_abttfix.max())}")
    w("")

    sel = parse_selected_layers()
    w("## Train-selected layers: baseline vs ABTT (non-T5 and all)")
    w("Layers from `overleaf_drafts/tables/selected_layers.tex` (Task A = argmax train AUROC, Task B = "
      "argmax train Dir@1). Recomputed argmax from the results CSV shown in brackets; ABTT = abtt_optimal. "
      "All values single-seed test scores from phase_resubmit_results.csv.")
    rb = r.copy()
    for m in ORDER:
        s = sel.get(m, {})
        rA_b = argmax_layer(rb, m, "baseline", "train_aucroc")
        rA_a = argmax_layer(rb, m, "abtt_optimal", "train_aucroc")
        rB_b = argmax_layer(rb, m, "baseline", "train_dir_acc_at_1")
        rB_a = argmax_layer(rb, m, "abtt_optimal", "train_dir_acc_at_1")
        la_b, la_a = s.get("A_base", rA_b), s.get("A_abtt", rA_a)
        lb_b, lb_a = s.get("B_base", rB_b), s.get("B_abtt", rB_a)
        d = df[df.m == m].set_index("layer")
        w(f"- {m}: Task A AUROC base {f3(d.loc[la_b, 'aucroc'])} (layer {la_b} [{rA_b}]) -> ABTT "
          f"{f3(d.loc[la_a, 'auc_abtt'])} (layer {la_a} [{rA_a}]); Task B assignment "
          f"{d.loc[lb_b, 'overall_assignment_acc'] * 100:.1f} -> {d.loc[lb_a, 'assign_abtt'] * 100:.1f}, "
          f"Dir@1 {d.loc[lb_b, 'dir_acc_at_1'] * 100:.1f} -> {d.loc[lb_a, 'dir1_abtt'] * 100:.1f} "
          f"(layers {lb_b} [{rB_b}] -> {lb_a} [{rB_a}])")
    w("")
    path.write_text("\n".join(L) + "\n")
    return L


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--facts_md", type=Path, default=Path("z1_numbers.md"))
    args = ap.parse_args()
    df, g, r = load()
    assert len(df) == 100, len(df)
    TAB_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    reg = regime_rows(df)
    ca = corr_rows(df, "aucroc")
    cg = corr_rows(df, "abtt_gain")
    write_regimes(reg, TAB_DIR / "geometry_regimes.tex")
    write_correlations(ca, cg, TAB_DIR / "geometry_correlations.tex")
    style()
    fig_scatter(df, FIG_DIR / "fig_geometry_vs_auroc")
    fig_sgap(df, FIG_DIR / "fig_standardized_gap")
    facts(df, r, reg, ca, cg, args.facts_md)
    print("wrote tables, figures and", args.facts_md)


if __name__ == "__main__":
    main()
